### ISSUE TITLE
Stop the old text clean-ups

### ISSUE THREAD

**Issue by fabiannorlin** [punktniklas/NiKom#4]
Today NiKom have a maximum of 32768 texts in the local meetings. When the 32768th text is written, NiKom automatically deletes the 512 oldest texts. It deletes the oldest Headxxx.dat and Textxxx.dat (where xxx holds the text number divided by 512) and change the value of Sysinfo('l').

I suppose this, once upon a time, was necessary for saving hard drive space, but today it is totally unnecessary.

The user data that keeps track of what texts has been read or not must be considered into changes for this. I suppose the easiest way is to make all older text handled as "read", but it would also be nice to make the what-have-been-read-database for each user to be able to handle more than 32768 texts.

**Comment by punktniklas** [comment]
I'm planning the following steps to fix this issue:
1. Refactor the code that deals with remembering what texts are unread. Right now it's spread out (and duplicated) everywhere. I want to put it into a well defined module.
2. Change the format of the "Bitmap0" file so that the range of the unread texts bitmap gets disconnected from the lowest text number in the system. I'm planning for this file to get auto-upgraded the first time  user logs into the new version, no conversion script to run. (This is the way I'd like things to be going forward so you don't have to have separate conversion programs and keep track of which goes with which version.)
3. Make the system able to handle "unlimited" number of texts. There will still be limitations since more texts will use more memory so it will still be possible to delete old texts. (Which btw will be much faster.)

With this plan there will still be a limitation that it can only remember the unread status for the latest 32768 texts. Older texts will be considered read. The refactorings being done should make this problem easier to tackle in the future though if needed.

**Comment by punktniklas** [comment]
The branch 'notextimit' has now been merged into master and the implementation of this issue is finished.
