### ISSUE TITLE
Problem with new user registration

### ISSUE THREAD

**Issue by jayminer81** [punktniklas/NiKom#53]
I got a message from a guest-user that it wasn't possible to register a new user by typing "ny" at the login screen. I tested from both a serial and a local node and it didn't work. I have tried with NEWUSERLOGIN = NY and NY = NY in System.cfg without any success, and the BBS is not closed. I noticed the same issue on Nikom BBS but it works to create a new user at Delta City.

**Comment by punktniklas** [comment]
The bug is in how NiKServer reads System.cfg. When trying to parse a configuration line it only looks at the beginning of the line for what it tries to match it against. So the line "NY=something" matches "NY" which is the (old Swedish) keyword for the new user config parameter. Further down in System.cfg there is the line "NYANV" (for configuring an ARexx script to run when a new user is registered). This will also match "NY" and overwrite the old value with this value. (Meaning that the ARexx script will never get configured..)

The solution to this bug is to make NiKServer match entire words. Since there is an easy workaround (use the new English keywords instead) I'm targeting the fix for 2.2.
