### ISSUE TITLE
Suggestion: Enhanced list of meetings

### ISSUE THREAD

**Issue by joacimmelin** [punktniklas/NiKom#55]
The current meeting list looks as thus: 

(Se) tiden --> li mö

  0 Information från SysOP  (Skrivskyddat) (Kom.skyddat) (Auto) (Skrivstyrt)
  0 Amiga
  0 BAD  (Slutet) (Hemligt)
  0 NiKom erfarenhetsutbyte
  0 Mötespresentationer  (Auto)    

It would be quite nice to be able to see the number of texts in each meeting. Like this: 

(Se) tiden --> li mö

0 / 67      Information från SysOP  (Skrivskyddat) (Kom.skyddat) (Auto) (Skrivstyrt)
0 / 2442  Amiga
1 / 341    NiKom erfarenhetsutbyte
0 / 55      Mötespresentationer  (Auto)    

where the first value is the number of unread texts and the latter is the total number of texts.

**Comment by punktniklas** [comment]
NiKom doesn't keep an easily available count of the number of texts in each (internal) forum. Since the texts are numbered globally and they are easily moved  from one forum to another you would have to count the number of texts every time you needed to present this number. Of course code could be added to keep this number cached and up to date all the time but I'm not sure the work and extra complexity would be worth it at this point.

I've been toying with the idea that it could be nice to have some kind of feature to be able to see what forums are active. (Not necessarily restricted to forums the user is a member of.) Not sure if this would be best as a part of Lista Möten or not though.
