### ISSUE TITLE
Can't unsubscribe to a meeting

### ISSUE THREAD

**Issue by joacimmelin** [punktniklas/NiKom#60]
Looks like a bug? 

Namn:            BBS Ads (Retronet)
Skapat av:       Joacim Melin #1
Skapat tid:      20160728  12:29
Mötesnummer:     165
Sorteringsvärde: 700
MAD:             Joacim Melin #1
Mötestyp:        FidoNet möte.
Tagnamn:         rtn_bbsads
Bibliotek:       mail:rtn_bbsads
Origin:          Delta City (deltacity.se, Vallentuna, Sweden)   

(Läsa) nästa text --> uttr BBS Ads (Retronet)

Du gick ur totalt 0 möten

(Läsa) nästa text --> uttr #165

Du gick ur totalt 0 möten

(Läsa) nästa text -->

**Comment by punktniklas** [comment]
As discussed on NiKom BBS. This is because these commands have support for wildcards and the "(" makes it think it's a wildcard, but it doesn't match anything.

We've decided to simply remove the wildcard support since it's based on AmigaDOS pattern matching which is a bit weird and something that almost no one knows nowadays.
