### ISSUE TITLE
Fidonet with Binkd

### ISSUE THREAD

**Issue by joacimmelin** [punktniklas/NiKom#8]
Has anyone tried running NiKOM with Binkd (Binkleyterm style but over Internet)?

I really want to get this running. 

Yes, I have no life. 

Joacim

**Comment by punktniklas** [comment]
I came across the name Binkd when I was trying to figure out what the status of Fidonet today is, but not much more than that.

Feel free to try to get it to work and write up a little howto on how you did it! I guess the approach would be to run everything except NiKom on the host side (Linux?) of an emulator to get texts downloaded, tossed etc. And then make sure they get written to a place in the file system where NiKom can access them. (And it should never know that it wasn't TrapToss that put them there. :-) )

I don't know if the FidoNet file formats have evolved lately. If not NiKom should in theory be able to read the files produced since it should be following the FTS basic standards. If there are issues let me know!

**Comment by joacimmelin** [comment]
After writing my initial question I discovered AmiBinkd (http://aminet.net/package/comm/net/amibinkd) which was updated back in 2012 (which is good news) and there are also an even later package (v6.00) but I'm having some issues finding that version for download. 

My plan is to run that and NiKOM on my A1200 on 12MB RAM and 20GB CF-storage and AmigaOS 3.1. With telnet access.  Yes, it is probably a stupid idea but still an idea worth trying.  :-)

If I understand it correctly the message flow would be AminBinkD -> TrapDoor -> NiKOM?

**Comment by punktniklas** [comment]
I only took a quick glance at AmiBinkd but it seems to be a full featured Fidonet mailer, using TCP/IP instead of dialup lines. So it would replace TrapDoor in an old setup. Also since it wouldn't need to share a phone line with NiKom it doesn't need to run as a frontend, the way TrapDoor had to do.

I think you still would need a tosser (like TrapToss) that takes the files that AmiBinkd has downloaded and unpacks them, puts message files in the right places, creates outgoing packets for other upstream/downstream nodes/points that you're talking to etc.

Who would be your upstream node?

And btw, NiKom is written "NiKom", not "NiKOM" :-)

**Comment by joacimmelin** [comment]
Okej då, NiKom, :-)

**Comment by joacimmelin** [comment]
Fidonet: I got in touch with Björn Felten (felten.yi.org) this spring and got myself a Fidonet node number (2:203/242).  I have verified that Amibinkd works fine connecting to Björns server. 

Now I need to install my memory expansion in my A1200 and then I will continue to work with NiKom and Amibinkd. Report will follow later this weekend!

**Comment by joacimmelin** [comment]
Memory expansion installed and BBS live at deltacity.se.  

Questions: 
how much RAM does each PreNode use?  I tried running three nodes on my 68020 A1200 and it did not work very well (the network I/O can't keep up). Two nodes is fine though. 

Just want to make sure Binkp fits into memory.

**Comment by punktniklas** [comment]
The PreNode should not use very much memory. More will be used when someone logs in and it launches NiKomSer though. To find out you could do this:
1. Start and then exit the PreNode so shared libraries get loaded.
2. Check available memory.
3. Start the PreNode and check again. The difference should be a pretty accurate figure of the memory usage.

How didn't it work when running three nodes? Were people logged in on them generating activity? If the nodes are just idle they shouldn't use any CPU at all. With a classic setup (= using modems and not any network) an Amiga 1200 shouldn't have any problems running three nodes. I have never been running a networked Amiga but I would suspect this is what eats resources.

So I assume you have gotten FidoNet to work? What tosser are you using?

**Comment by punktniklas** [comment]
Btw, what version of telnetd.device are you using? When I tried with the free demo version (1.0) the system became more or less unusable. A later version worked much better.

**Comment by joacimmelin** [comment]
(I think) I'm currently using version 0 rev 165.  There are way newer ones on AmiNet so I'm going to upgrade it today. 

Haven't got Fidonet working yet. Also a project for today. :)

**Comment by punktniklas** [comment]
Can you check which version of telnetd.device that is? You can look inside the file with e.g. the strings command and you should find it in the beginning of the file. There are strings implementations for Amiga and it's standard on any Unix system.

I just created a page with additional software downloads on www.nikom.org where I put up the two versions I have.

**Comment by joacimmelin** [comment]
I'm running v1.91.

**Comment by punktniklas** [comment]
I'm closing this discussion thread issue.  Please continue on NiKom BBS if needed. :-)
